### ISSUE TITLE
Recovery Mode

### ISSUE THREAD

**Issue by jantoonen** [mwolfinspace/Hackintosh-HP-Pavilion-15-cs2033TU#1]
First I would like to thank you for your effort. It enabled me to upgrade my Opencore environment from 0.6.9 to 0.7.5 without much work. THANKS!!

I run howver in an issue. I need to install 2 kext files and hence need SIP to be disabled which means boot in recovery mode. And the config as us does not allow me to do so. Have you the same problem? Suggestions how to fix?

Regards

Jan Toonen

**Comment by mwolfinspace** [comment]
To enable/disable SIP, you may follow this [guide on OpenCore](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/post-issues.html#disabling-sip). In short, edit the c**sr-active-config** value and add **csr-active-config** to the Delete Section of _NVRAM_. So we don't have to boot in the Recovery Mode to change the SIP status.

By the way, the recovery mode works fine with Big Sur and older. I'm still trying to make it work on Monterey (12.0.1).
Turning off the SIP is not recommended, so I wonder what kexts you would like to install directly to the filesystem?

Regards

Phu Nguyen

**Comment by jantoonen** [comment]
Hello

Thanks for your prompt reaction.

What I try to do is to get my external usb wifi adapter to work with this software:
https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter

I finally managed to get the adapter to work by including the kext files in the config.plist AND by copying them to the /Library/Extension folder. And then installing the old installation package for the driver tp-link program (ends with an error, but works anyhow), so no SIP disabling….as the new version requires….

I am glad to learn that the issue with booting from recovery is not something specific to my setup. Time will tell if this will get resolved….

Again may thanks for your work on the OpenCore 0.7.5 configuration. It was a great starting point to get my config working with minimal changes.

Regards from a rainy The Netherlands,

Jan Toonen
